# Generated by Django 5.2.3 on 2025-07-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_inicial', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidades'), ('MTR', 'Metros'), ('CM', 'Centímetros'), ('KG', 'Kilogramos'), ('GR', 'Gramos'), ('LT', 'Litros'), ('ML', 'Mililitros'), ('CJ', 'Cajones'), ('PAQ', 'Paquete'), ('ROL', 'Rollo'), ('BLT', 'Balde/Tarro')], default='UND', max_length=3)),
                ('tipo_adquisicion', models.CharField(choices=[('F1', 'Fabricación'), ('M1', 'Compra/Venta')], default='M1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
